### ISSUE TITLE
ydiff 1.4 FileNotFoundError: [Errno 2] No such file or directory: 'CHANGES.rst'

### ISSUE THREAD

**Issue by foot3print** [ymattw/ydiff#123]
Hi, just today i wanted to install ydiff over pip and failed with the following error.

...
Collecting ydiff
  Using cached https://firm-internal-repo/artifactory/api/pypi/common-python-pypi-remote/packages/packages/ea/d8/7a5ac7c290829830cbc191b826ad4187e0014882c8a7c3d43bbf28e615d9/ydiff-1.4.tar.gz (15 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  Ã python setup.py egg_info did not run successfully.
  â exit code: 1
  â°â> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-zfyso4zq/ydiff_7368b72a2c9a410f8b411801c9d0b539/setup.py", line 9, in <module>
          with open('CHANGES.rst') as changes:
      FileNotFoundError: [Errno 2] No such file or directory: 'CHANGES.rst'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Ã Encountered error while generating package metadata.
â°â> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Upon downloading the ydiff 1.4 and unpacking it, I found out that the file CHANGES.rst is indeed missing in the package. Can you please add the file to the release?

**Comment by ymattw** [comment]
Oops, sorry for that. Turns out the package does not contain `CHANGES.rst` anymore. I will have to add it back maybe without a `MANIFEST.in` file. I will fix this soon.

**Comment by ymattw** [comment]
Had to bump up the version and publish `1.4.1`. Could you try again?
