### ISSUE TITLE
How to use on Windows

### ISSUE THREAD

**Issue by sergeevabc** [ymattw/ydiff#96]
Dear @ymattw, have a look at this, please.

Windows 7 x64, Python 3.8.1

```console
$ pip install --upgrade ydiff               
Collecting ydiff                                             
  Downloading ydiff-1.1.tar.gz (36 kB)                       
Installing collected packages: ydiff                         
    Running setup.py install for ydiff ... done              
Successfully installed ydiff-1.1                             
                                                             
$ ydiff abc cba                                     
'ydiff' is not recognized as an internal or external command,
operable program or batch file.                              
```

**Comment by johnd0e** [comment]
It is installed as script with name `ydiff` (without extension).
I'd be possible to run it with `python.exe ydiff`, but it seems Windows is not supported:
```
Traceback (most recent call last):
  File "ydiff", line 7, in <module>
    sys.exit(ydiff.main())
  File "C:\APPs\Development\WinPython\python-3.8.0\lib\site-packages\ydiff.py", line 794, in main
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
AttributeError: module 'signal' has no attribute 'SIGPIPE'
```

**Comment by johnd0e** [comment]
To install `ydiff` command into git:

1. Make sure that python directory is in PATH
2. In directory `git\usr\bin\` create file `git-ydiff`:
   ```py
   #!/usr/bin/env python

   import sys
   import ydiff
   sys.exit(ydiff.main())
   ```
3. All is done!
   Run `git ydiff`

**Comment by sergeevabc** [comment]
ydiff 1.1 outputs much like you posted above. I believe the patch you advertised earlier should be applied to roll out 1.2, huh?
```console
[18:34] C:\Python\Scripts $ py ydiff
Traceback (most recent call last):
  File "ydiff", line 7, in <module>
    sys.exit(ydiff.main())
  File "c:\python\lib\site-packages\ydiff.py", line 794, in main
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
AttributeError: module 'signal' has no attribute 'SIGPIPE'
```

**Comment by ymattw** [comment]
Ydiff is never declared supporting Windows.  I see the "'ydiff' is not recognized as an internal or external command" problem is already answered, so going to close this. The SIGPIPE problem is tracked in #81.

Truly sorry for not able to answer earlier.
